name: vma
python_version: "3.10"
ci:
  run_lint: false
  run_tests: true
  run_security: true
  run_security_sca: true
  security_fail_on_error: true
  security_export_sarif: true
  run_publish: false
