services:
  db:
    image: postgres:latest
    restart: always
    env_file:
    - .env
    volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    - pgdata:/var/lib/postgresql/

  init_db_nvd:
    image: vma:latest
    env_file:
    - .env
    command: ["cve", "--init"]
    depends_on:
    - db

  init_db_osv:
    image: vma:latest
    env_file:
    - .env
    command: ["osv", "--all"]
    depends_on:
    - db

  init_login:
    image: vma:latest
    env_file:
    - .env
    command: ["login", "--init"]
    depends_on:
        init_db_nvd:
            condition: service_completed_successfully

  rev_proxy:
    build:
      context: rev_proxy/
      dockerfile: Dockerfile
    restart: always
    ports:
    - "8443:443"
    - "8080:80"
    networks:
      default:
        aliases:
          - vma.local
          - www.vma.local

  web:
    image: web:latest
    env_file:
    - .env
    depends_on:
    - rev_proxy
    restart: always

volumes:
  pgdata:
